[tool.ruff]
line-length = 100
target-version = "py311"
exclude = ["allure-results", "reports", ".venv", "venv", "__pycache__"]

[tool.ruff.lint]
select = ["E", "F", "I", "UP"]

[tool.black]
line-length = 100
target-version = ["py311"]

[tool.isort]
profile = "black"
line_length = 100
skip = ["allure-results", "reports", ".venv", "venv", "__pycache__"]
